### ISSUE TITLE
Add support for other styles as well

### ISSUE THREAD

**Issue by valleybay** [Angelmmiguel/material_icons#27]
Material Icons currently come in five different styles:
- Filled
- Outlined
- Rounded
- Two-tone
- Sharp

As seen [here](https://material.io/tools/icons/?style=round).

Are there any plans to add support for these?

**Comment by Angelmmiguel** [comment]
Hello @valleybay,

This gem is based on the [font family of Material Icons](https://github.com/google/material-design-icons/tree/master/iconfont) and they didn't release any font for the new styles yet. I'm suscribed to [material-design-icons/773](https://github.com/google/material-design-icons/issues/773), so when they release the new font-family I'll start working on adding it to the gem 😄

**Comment by Angelmmiguel** [comment]
@valleybay just to give you an update, Google team has already confirmed they will release the font family of the other icon styles. They don't have any deadline, but it's good to know they will work on it :)

**Ref**: https://github.com/google/material-design-icons/issues/773#issuecomment-422112308

**Comment by valleybay** [comment]
Great! Thanks for the update! :-)

**Comment by EchoUrandom** [comment]
Any updates on this?

**Comment by Angelmmiguel** [comment]
Hello!

Fortunately, there's some news on this @EchoUrandom. 5 days ago a user noticed the material.io site is using the icon font instead of the inline SVGs 🎉 : https://github.com/google/material-design-icons/issues/773#issuecomment-530863779.

For now, it seems they're working on it because there isn't any official announcement about it. Also, [the icon font familes are not in the repository yet](https://github.com/google/material-design-icons/tree/master/iconfont). I expect/hope they start adding them soon so I can add to this gem too.

🤞

**Comment by theSoenke** [comment]
Hi @Angelmmiguel, the repository now seems to include all styles https://github.com/google/material-design-icons/tree/master/font Would be fantastic if these could be added in a new release of the gem

**Comment by Angelmmiguel** [comment]
I published the new v4.0.0 version of the gem! It includes all the new styles as well as other improvements. Here you can find all the release notes :) https://github.com/Angelmmiguel/material_icons/releases/tag/v4.0.0
